Repository playframework/twirl, pull requests merged in 2022-11, with the labels that each got.

#566 scalafmt-core 3.6.1 (was 3.6.0)
  .scalafmt.conf
Labels: type:updates

#567 Remove deprecated pieces of code
  api/shared/src/main/scala/play/twirl/api/TemplateMagic.scala
  build.sbt
  parser/src/main/scala/play/twirl/parser/TwirlParser.scala
  sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala
  sbt-twirl/src/main/scala/play/twirl/sbt/TemplateCompiler.scala
Labels: status:merge-when-green

#570 sbt 1.8.0 (was 1.8.0-RC1)
  docs/project/build.properties
  project/build.properties
Labels: type:updates

#569 scala3-compiler, scala3-library, ... 3.2.1 (was 3.2.0)
  project/Dependencies.scala
Labels: type:updates

#573 sbt-header 5.9.0 (was 5.8.0)
  docs/project/plugins.sbt
  project/plugins.sbt
Labels: type:updates

#574 sbt-scalafmt 2.5.0 (was 2.4.6)
  docs/project/plugins.sbt
  project/plugins.sbt
Labels: type:updates, status:merge-when-green
